services:
  - type: worker
    name: bot-kwai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
    pythonVersion: 3.11
